### ISSUE TITLE
Stock firmware link is down

### ISSUE THREAD

**Issue by PowderLinux** [amit-raut/Onn.-4k-Streaming-Box-Rooting-and-Remote-Button-Remapping#3]
The link that you posted to the stock firmware is down..
I have a copy of it on my cloud account if anyone needs it.

File: dopinder-qt.20210519-factory.zip
MD5: 08fa86ced3da6c50aafe8395fce27fe9
https://u.pcloud.link/publink/show?code=XZvdNJ0ZpUYLpHQ4H986VavfRg5RnkphLuIk

**Comment by amit-raut** [comment]
Thanks @PowderLinux. I'll update the README with the link you shared.
